version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    # pdm export -G docs -f requirements -o docs/requirements.txt
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
